CREATE DATABASE IF NOT EXISTS kopma_018
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'mhs_018'@'localhost' IDENTIFIED BY 'zalfamhs251106';

GRANT ALL PRIVILEGES ON kopma_018.* TO 'mhs_018'@'localhost';

FLUSH PRIVILEGES;